// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'employee.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$EmployeeImpl _$$EmployeeImplFromJson(Map<String, dynamic> json) =>
    _$EmployeeImpl(
      id: json['id'] as int,
      staffCode: json['staffCode'] as String,
      name: json['name'] as String,
      userName: json['userName'] as String,
      rank: json['rank'] as int,
      managerId: json['managerId'] as int,
      dateOfBirth: json['dateOfBirth'] as String?,
      nationalId: json['nationalId'] as String?,
      dateOfIssue: json['dateOfIssue'] as String?,
      placeOfIssue: json['placeOfIssue'] as String?,
      expiredDate: json['expiredDate'] as String?,
      email: json['email'] as String?,
      companyEmail: json['companyEmail'] as String?,
      education: json['education'] as String?,
      taxCode: json['taxCode'] as String?,
      socialInsuranceId: json['socialInsuranceId'] as String?,
      healthInsureanceId: json['healthInsureanceId'] as String?,
      emergencyUser: json['emergencyUser'] as String?,
      emergencyPhone: json['emergencyPhone'] as String?,
      ethnic: json['ethnic'] as String?,
      gender: json['gender'] as int?,
      hireDate: json['hireDate'] as String?,
      staOfficeDate: json['staOfficeDate'] as String?,
      leaveDate: json['leaveDate'] as String?,
      staffStatus: json['staffStatus'] as int?,
      nationality: json['nationality'] as String?,
      phone: json['phone'] as String?,
      religion: json['religion'] as int?,
      bankAccountNumber: json['bankAccountNumber'] as String?,
      bankName: json['bankName'] as String?,
      address: json['address'] as String?,
      imageUrl: json['imageUrl'] as String?,
      specializes: json['specializes'] as int?,
      teamId: json['teamId'] as int?,
      positionId: json['positionId'] as int?,
      isDeleted: json['isDeleted'] as int,
      departmentId: json['departmentId'] as int?,
      decentralization: json['decentralization'] as String?,
      createdBy: json['createdBy'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedBy: json['updatedBy'] as String?,
      updatedAt: json['updatedAt'] as String?,
      departmentName: json['departmentName'] as String?,
      teamName: json['teamName'] as String?,
      managerName: json['managerName'] as String?,
      positionName: json['positionName'] as String?,
      contractName: json['contractName'] as String?,
    );

Map<String, dynamic> _$$EmployeeImplToJson(_$EmployeeImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'staffCode': instance.staffCode,
      'name': instance.name,
      'userName': instance.userName,
      'rank': instance.rank,
      'managerId': instance.managerId,
      'dateOfBirth': instance.dateOfBirth,
      'nationalId': instance.nationalId,
      'dateOfIssue': instance.dateOfIssue,
      'placeOfIssue': instance.placeOfIssue,
      'expiredDate': instance.expiredDate,
      'email': instance.email,
      'companyEmail': instance.companyEmail,
      'education': instance.education,
      'taxCode': instance.taxCode,
      'socialInsuranceId': instance.socialInsuranceId,
      'healthInsureanceId': instance.healthInsureanceId,
      'emergencyUser': instance.emergencyUser,
      'emergencyPhone': instance.emergencyPhone,
      'ethnic': instance.ethnic,
      'gender': instance.gender,
      'hireDate': instance.hireDate,
      'staOfficeDate': instance.staOfficeDate,
      'leaveDate': instance.leaveDate,
      'staffStatus': instance.staffStatus,
      'nationality': instance.nationality,
      'phone': instance.phone,
      'religion': instance.religion,
      'bankAccountNumber': instance.bankAccountNumber,
      'bankName': instance.bankName,
      'address': instance.address,
      'imageUrl': instance.imageUrl,
      'specializes': instance.specializes,
      'teamId': instance.teamId,
      'positionId': instance.positionId,
      'isDeleted': instance.isDeleted,
      'departmentId': instance.departmentId,
      'decentralization': instance.decentralization,
      'createdBy': instance.createdBy,
      'createdAt': instance.createdAt,
      'updatedBy': instance.updatedBy,
      'updatedAt': instance.updatedAt,
      'departmentName': instance.departmentName,
      'teamName': instance.teamName,
      'managerName': instance.managerName,
      'positionName': instance.positionName,
      'contractName': instance.contractName,
    };
